### ISSUE TITLE
List command should return users in a table format

### ISSUE THREAD

**Issue by potsbo** [wantedly/github-username-converter#25]
## WHY

Current list command returns users in the format below.
```
shimpei:@potsbo:<@XXXXXXXXX|shimpei>
```
It's hard to tell which one is for which account.

## WHAT

We should consider some format that both humans and programs can parse easily.

### Candidates
- tsv
- csv
- own table format (perhaps using some go lib)

@dtan4 How do you think about these candidates?
If you know any good method to render in table format with Golang, that would be great.
I haven't looked into anything yet.

**Comment by dtan4** [comment]
I prefer TSV.

Golang has [text/tabwriter](https://golang.org/pkg/text/tabwriter/) package. It would help you to implement TSV generator.

**Comment by potsbo** [comment]
Implemented
