### ISSUE TITLE
Introduce Test

### ISSUE THREAD

**Issue by potsbo** [wantedly/github-username-converter#8]
## WHY

As mentioned at https://github.com/wantedly/developers-account-mapper/pull/6 and https://github.com/wantedly/developers-account-mapper/pull/7
We need automatic tests to prevent bugs being merged to master.

## WHAT

- [x] Add a testing framework
- [ ] Write tests for already-implemented features
- [x] Add CI services

**Comment by dtan4** [comment]
I highly recommend to use standard `testing` package, NOT to use any other 3rd-party testing frameworks. This thought is common among Golang community.

## REF

- [Go の Test に対する考え方 - Qiita](http://qiita.com/Jxck_/items/8717a5982547cfa54ebc)
- [Goとテスト](http://www.slideshare.net/takuyaueda967/go-53217449)

**Comment by potsbo** [comment]
Though there are still some implementations that are not tested, it's working fine.
